[add] Feature/add userresponsejson linkedinscraper
MasakiNishi/job-hunting-ai-backend pull request #6
Opened 2024-07-26 15:32 UTC by alewon413

## Description

This submission seeks to convert frontend response/form submission to JSON, and includes a general LinkedIn scraper that uses query parameters and the LinkedIn API/guest access to do general scraping (parameters being sector and location from the frontend).

## Related Issue

JIRA: [KAN-24](https://oregonstate-team-a4gvoaif.atlassian.net/browse/KAN-24)

## Motivation and Context

This change is necessary since it initializes our process in converting user response to a digestible JSON format, as well as get our group started on how we can scrape LinkedIn job postings and playing around with the necessary query parameters.

## How Has This Been Tested?

For user_response.py:
-The frontend was initialized via terminal (npm start)
-Script was initialized via terminal (python user_response.py)
-On frontend submission, responses were saved in a JSON file under backend directory (./text_JSON/user_answers.json)

For linkedin_scraper.py:
-Using test query parameters (can be changed in the link in the code), altered different sectors and locations
-Confirmed with different parameters that different postings would appear (though more testing is needed across days to see if postings will be different)
***Definitely needs more testing and refining, not yet connected to what is provided in user_response.py for dynamic scraping

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x ] My code follows the code style of this project.
- [ x ] I have commented my code, particularly in hard-to-understand areas.
- [ x ] My changes generate no new warnings.
- [ ] I have added tests to cover my changes.
- [ x ] I have passed lints.
- [ ] All new and existing tests passed.

## Further comments

This would be considered a large change since it's an addition of a new feature, but I tried to comment the code as much as possible. Definitely more work needs to be done, feel free to make any changes as necessary!

2024-07-26 21:21 UTC, MasakiNishi requested changes
Thank you for making these changes!

Overall, it would be helpful if the initial design adheres to OOP (Object-Oriented Programming) and DRY (Don't Repeat Yourself) principles. This approach will make it easier to create additional files in the future. I've added specific comments to each file for your review. Please take a look at them.

2024-07-26 21:21 UTC, MasakiNishi commented on .env.local
Can you create a feature branch by pulling from the main branch?
This branch is pulled from my past gemini feature branch, so it contains differences in files unrelated to the changes in this feature branch.

2024-07-26 21:21 UTC, MasakiNishi commented on user_response.py
I believe it is generally more common to keep user responses in memory and pass them as arguments to other functions rather than storing them in JSON files. Using files for this purpose can require many operations such as file locking, overwriting, and clearing, which might lead to potential errors since these operations are not currently implemented.

2024-07-26 21:21 UTC, MasakiNishi commented on text_JSON/linkedin_jobs.json
Shouldn't the scraped information include job descriptions and other details? I noticed that the scraped content contains URLs, but currently, generative AIs like Gemini cannot scrape and fetch information from URLs. Therefore, the scraped content should include as much plain text information as possible to be effective.

2024-07-26 21:21 UTC, MasakiNishi commented on scrape_linkedin.py
It might be beneficial to consolidate common tasks such as sending GET requests to websites and parsing responses, converting formatted information into pandas DataFrame and saving to JSON files into a separate file as shared functions. This way, these functions can be imported and used in any file, reducing the need to rewrite the same processes across different files.
Currently, the same processes need to be written in multiple files. Ideally, only the site-specific scraping and formatting of unique information should remain in each respective file.

2024-07-27 02:09 UTC, alewon413 commented on text_JSON/linkedin_jobs.json
I pulled the URLs since I thought that was what we would display to the users when the process was complete and the jobs are shown to the users. I'm aware that generative AIs cannot scrape and fetch info from URLs.

2024-07-27 02:11 UTC, alewon413 commented on .env.local
Just did this, hopefully it went through

2024-07-27 02:15 UTC, alewon413 commented on user_response.py
That makes sense, I can simply remove the file writing and store them in the jobs_list as is. Am I understanding that correctly?

2024-07-27 02:16 UTC, alewon413 commented on text_JSON/linkedin_jobs.json
I also added the job description scrape, I totally blanked out on including that! What other details do you think we should include?

2024-07-27 02:19 UTC, alewon413 commented on scrape_linkedin.py
Yes that makes sense, I was just thinking to have it set up with one file since I'm not too aware of how other job site APIs function (but it should be relatively the same). Would definitely make building the backend much easier.

2024-07-27 07:23 UTC, MasakiNishi commented on scrape_linkedin.py
I see that you have implemented the ScraperUtils. This will definitely make the implementation in other files much easier. Thank you for doing this!

2024-07-27 07:24 UTC, MasakiNishi commented on text_JSON/linkedin_jobs.json
You're right, displaying the URLs to users is necessary. Including the job descriptions is sufficient for now. Great job on adding that!

2024-07-27 07:25 UTC, MasakiNishi commented on user_response.py
Yes, that's what I was thinking!

2024-07-28 02:41 UTC, alewon413 commented on user_response.py
Got it, thanks for confirming!

2024-07-28 02:41 UTC, alewon413 commented on text_JSON/linkedin_jobs.json
Got it, thanks for confirming!

2024-07-28 02:42 UTC, alewon413 commented on scrape_linkedin.py
Thanks for the suggestion!

2024-07-28 06:12 UTC, JohSus approved these changes, later dismissed

2024-07-28 06:12 UTC, JohSus commented on user_response.py
If I'm understanding correctly, we're saving the scraped data, which we're then using pandas to clean up the scraped data, to send the results back to the user. So our json file wouldn't be user responses.

2024-07-28 06:12 UTC, JohSus commented on user_response.py
I see that there's a linkedin_jobs.json file. Is that the result from the test json file?

2024-07-28 07:57 UTC, christianmckinnon reviewed
I'm going to defer to Masaki and Susan on this as they have been working on this repo over the last couple of weeks.

2024-07-28 08:15 UTC, MasakiNishi commented on user_response.py
I was talking about user_answers, not job_lists. I am commenting on the user_response.py file, so consider my comment about this file.

2024-08-04 08:23 UTC, MasakiNishi commented on user_response.py
Fixed in https://github.com/MasakiNishi/job-hunting-ai-backend/pull/7

2024-08-04 08:23 UTC, MasakiNishi approved these changes

2024-08-04 09:39 UTC, christianmckinnon commented
Merging based off of Masaki's approval.

2024-08-04 09:39 UTC, merged